---
- name: "Create user {{ username }}"
  user:
    name: "{{ username }}"
    comment: "{{ full_name }}"
    shell: "{{ user_shell | default('/bin/bash') }}"
    state: present

- name: "Add authorized key to {{ username }}"
  authorized_key:
    user: "{{ username }}"
    key: "{{ public_key }}"
    state: present